    name: My Automation Bot

    on:
      push:
        branches:
          - main

    jobs:
      automate-task:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Run automation script
            run: |
              echo "foo" > example.txt

          - name: Commit and push changes
            run: |
              git config user.name 'github-actions[bot]'
              git config user.email 'github-actions[bot]@users.noreply.github.com'
              git add .
              git commit -m "Automated changes by bot"
              git push
