name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/release.yml"
      - "docs/**"
      - "*.md"
      - "LICENSE"
      - ".cursorrules"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/release.yml"
      - "docs/**"
      - "*.md"
      - "LICENSE"
      - ".cursorrules"

jobs:
  all-features-build:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build and test with all features
        run: cargo test --all-features --verbose
